# Dependencies
markdown:         kramdown
highlighter:      rouge
mathengine:       mathjax

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            Nils Droste
tagline:          'a personal page'
description:      'researching sustainable land use governance'
url:              https://nils.droste.io
# urlimg:           https://nils.droste.io/pics/
baseurl:          ''
paginate:         5

# About/contact
author:
  name:           'Nils Droste'
  email:          'nils@droste.io'
  email_md5:      b577d4be434dd451a33f01e111e906b5
  #twitter:        NilsDroste
  researchgate:   Nils_Droste
  github:         NilsDroste
  orcid:          https://orcid.org/0000-0003-4357-9115
  google_scholar: https://scholar.google.de/citations?hl=de&user=oHRPDwcAAAAJ

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/lanyon

# Gems
gems:		          [jekyll-paginate, jekyll-gist]

# Collections
collections:
  pics:
    output:       true
  research:
    output:       true

# # Include
# include :
#   - _research
